apiVersion: v1
kind: Service
metadata:
  name: db-connect-nodeport-service
#  namespace: dev
spec:
  ports:
  - port: 30025
    nodePort: 30025
    targetPort: nginx-port
    protocol: TCP
  selector:
    app: db-connect
  type: NodePort